"""Disjoint synthetic tooling checks; no selected pilot term is constructed."""

import json
import unittest

from lib.resource_envelope_producer import (
    ProducerError, canonical_json, case_id, declaration_name,
    render_source, render_value, selected_slots, value_metrics,
)


class ResourceEnvelopeProducerTests(unittest.TestCase):
    def test_selected_schedule_only(self):
        slots = selected_slots()  # Ordinals, not scientific input construction.
        self.assertEqual(len(slots), 12)
        self.assertEqual(slots[0], (0, "pi", 16))
        self.assertEqual(slots[-1], (11, "let", 512))
        self.assertEqual(case_id("pi", 3), "rep1-pi-003")
        self.assertEqual(declaration_name("let", 3), "ResourceEnvelopePilot1.let003")

    def test_synthetic_source_grammar(self):
        self.assertEqual(render_value("pi", 2),
                         "(forall (x000 : Sort 0), (forall (x001 : Sort 0), Sort 0))")
        self.assertEqual(render_value("let", 2),
                         "(let x000 : Sort 1 := Sort 0; (let x001 : Sort 1 := x000; x001))")
        self.assertEqual(render_source("pi", 2),
                         b"-- Generated by resource-envelope-pilot-1; exact scientific input.\n"
                         b"namespace ResourceEnvelopePilot1\n\n"
                         b"def pi002 : Sort 1 := (forall (x000 : Sort 0), "
                         b"(forall (x001 : Sort 0), Sort 0))\n\n"
                         b"end ResourceEnvelopePilot1\n")

    def test_synthetic_graph_metrics(self):
        # Hand-written two-binder Pi graph. The same Sort 0 node is shared.
        export = (
            b'{"meta":{}}\n'
            b'{"ie":0,"sort":0}\n'
            b'{"ie":1,"forallE":{"type":0,"body":0}}\n'
            b'{"ie":2,"forallE":{"type":0,"body":1}}\n'
            b'{"def":{"value":2}}\n'
        )
        self.assertEqual(value_metrics(export), (3, 5))

    def test_reject_malformed_and_bool_indices(self):
        for value in (True, -1, 1000):
            with self.assertRaises(ProducerError):
                render_value("pi", value)
        with self.assertRaises(ProducerError):
            value_metrics(b'{"ie":0,"ie":1}\n')
        with self.assertRaises(ProducerError):
            value_metrics(b'{"ie":true,"sort":0}\n{"def":{"value":0}}\n')

    def test_canonical_json(self):
        self.assertEqual(canonical_json({"z": 1, "a": 2}), b'{"a":2,"z":1}\n')
        self.assertEqual(json.loads(canonical_json({"x": 4})), {"x": 4})


if __name__ == "__main__":
    unittest.main()
