"""Fixed CVC-U1 declaration skeletons and conservative Lean output parsing.

The Lean compiler and reviewed proof source remain trusted. This narrow source
admission policy rejects audit-generating commands; it is not a Lean parser or
a sandbox for adversarial metaprograms.
"""
import re

TARGETS = [
    ('Lab.CVC2.encoding_preserves', 'Lab.CVC2.EncodingTarget'),
    ('Lab.CVC2.preservation', 'Lab.CVC2.PreservationTarget'),
    ('Lab.CVC2.required_acceptance', 'Lab.CVC2.AcceptanceTarget'),
    ('Lab.CVC2.boundary', 'Lab.CVC2.BoundaryTarget'),
]
NEGATIVE = [('Lab.CVC2.counterexample',
             '∃ a : Lab.CVC2.SortDefinition, Lab.CVC2.Accepts a ∧ ¬ Lab.CVC2.Contract a')]
COMPARATORS = ["Lean.Level.isEquiv'_wf", "Lean.Level.isEquiv'_complete"]


def require(ok, message):
    if not ok:
        raise ValueError(message)


def targets(mode):
    require(mode in {'proof', 'counterexample'}, 'unknown result mode')
    return TARGETS if mode == 'proof' else NEGATIVE


def strip_comments(text):
    """Keep line structure; nested comments cannot spoof a theorem declaration."""
    out, i, depth = [], 0, 0
    while i < len(text):
        if text.startswith('/-', i):
            depth += 1; out.extend('  '); i += 2
        elif depth and text.startswith('-/', i):
            depth -= 1; out.extend('  '); i += 2
        elif depth:
            out.append('\n' if text[i] == '\n' else ' '); i += 1
        elif text.startswith('--', i):
            end = text.find('\n', i)
            end = len(text) if end < 0 else end
            out.extend(' ' * (end - i)); i = end
        else:
            # Strings/quoted identifiers can introduce forged audit commands or
            # hide command boundaries. This proof-only subset does not need them.
            require(text[i] not in '"«»`', 'strings or syntax quotations outside admitted proof subset')
            out.append(text[i]); i += 1
    require(depth == 0, 'unterminated comment')
    return ''.join(out)


def suffix(mode):
    declarations = targets(mode)
    return ('\n-- Fixed CVC3-U1-PROOF-0001 audit; generated by the bound runner.\n'
            + '\n'.join(f'example : {typ} := {name}' for name, typ in declarations) + '\n'
            + '\n'.join(f'#print axioms {name}' for name in [n for n, _ in declarations] + COMPARATORS) + '\n')


def generate(text, mode='proof'):
    clean = strip_comments(text)
    lines = [line.strip() for line in clean.splitlines() if line.strip()]
    require(lines and lines[0] == 'import Contract', 'exact Contract import must come first')
    require(len(re.findall(r'\bimport\b', clean)) == 1, 'additional import forbidden')
    forbidden = (r'\b(?:axiom|sorry|sorryAx|admit|native_decide|ofReduceBool|ofReduceNat|unsafe|'
                 r'run_tac|run_elab|elab|macro|syntax|initialize|builtin_initialize|'
                 r'set_option|namespace|section|variable|variables|opaque|attribute|'
                 r'notation|local|scoped|export)\b|[#]')
    require(re.search(forbidden, clean) is None, 'forbidden proof or audit construct')
    for name, typ in targets(mode):
        pattern = r'(?m)^theorem\s+' + re.escape(name) + r'\s*:\s*' + re.escape(typ) + r'\s*:='
        require(len(re.findall(pattern, clean)) == 1, 'missing or wrong fixed theorem type: ' + name)
    return (text.rstrip() + '\n' + suffix(mode)).encode()


def audit(stdout, stderr, assumptions, mode='proof'):
    require('sorry' not in (stdout + stderr).lower(), 'sorry diagnostic or axiom')
    allowed = set(assumptions['conditional_axiom_policy']['standard_allowed']
                  + assumptions['conditional_axiom_policy']['source_helpers_allowed'])
    names = [n for n, _ in targets(mode)] + COMPARATORS
    # Greedy name capture on a single line handles isEquiv'_wf's apostrophe.
    pattern = re.compile(r"^'([^\n]+)' (?:does not depend on any axioms|depends on axioms:\s*(\[[^\]]*\]))[ \t]*$", re.M)
    reports, used = {}, []
    for match in pattern.finditer(stdout):
        name, listing = match.group(1), match.group(2)
        require(name in names and name not in reports, 'unexpected or duplicate axiom report')
        entries = [] if listing is None or listing == '[]' else [x.strip() for x in listing[1:-1].split(',')]
        require(all(re.fullmatch(r"[A-Za-z_][A-Za-z_0-9']*(?:\.[A-Za-z_][A-Za-z_0-9']*)*", x) for x in entries),
                'malformed full axiom list')
        require(len(entries) == len(set(entries)), 'duplicate axiom')
        require(set(entries) <= allowed, 'unlisted axiom: ' + ', '.join(sorted(set(entries) - allowed)))
        reports[name] = entries; used.append(match.span())
    require(set(reports) == set(names), 'missing required full axiom report')
    remainder = stdout
    for start, end in reversed(used):
        remainder = remainder[:start] + remainder[end:]
    require(not re.search(r'depends on axioms|does not depend on any axioms', remainder), 'malformed extra axiom report')
    return {'mode': mode, 'declarations': [{'name': n, 'type': t} for n, t in targets(mode)],
            'transitive_axioms': reports, 'conditional': True}
