"""Independent validity, identity, and size auditor for RESOURCE-ENVELOPE-PILOT-1.

This module reads the frozen case protocol but imports no producer, term builder,
export parser, or expected-result implementation. It verifies one safe definition
from exact source/export bytes, then separately enforces the fixed 12-case cohort.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path, PurePosixPath
import re
from typing import Any


ITEM_ID = "RESOURCE-ENVELOPE-PILOT-1"
CASE_KEYS = {"schema_version", "id", "ordinal", "family", "size", "declaration",
             "expected_type", "source", "export", "metrics"}
REF_KEYS = {"path", "bytes", "sha256"}
METRIC_KEYS = {"serialized_bytes", "reachable_dag_nodes", "expanded_value_nodes",
               "binder_depth", "dependency_declarations"}
INDEX_KEYS = {"schema_version", "item_id", "cases"}
INDEX_ROW_KEYS = {"id", "ordinal", "family", "size", "case"}
HEX64 = re.compile(r"[0-9a-f]{64}\Z")


class AuditError(ValueError):
    """Stable machine-readable audit failure."""

    def __init__(self, code: str, message: str):
        self.code = code
        super().__init__(f"{code}: {message}")


def _fail(code: str, message: str) -> None:
    raise AuditError(code, message)


def _natural(value: Any, label: str) -> int:
    if type(value) is not int or value < 0:
        _fail("E_NATURAL", f"{label} must be a natural integer")
    return value


def _exact(value: Any, keys: set[str], label: str) -> dict[str, Any]:
    if type(value) is not dict or set(value) != keys:
        _fail("E_SCHEMA", f"{label} keys differ")
    return value


def _json_pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key, value in pairs:
        if key in out:
            _fail("E_DUPLICATE_KEY", f"duplicate JSON key {key!r}")
        out[key] = value
    return out


def _nonfinite(token: str) -> None:
    _fail("E_JSON", f"non-finite JSON value {token}")


def _canonical(value: Any) -> bytes:
    try:
        return json.dumps(value, sort_keys=True, separators=(",", ":"),
                          ensure_ascii=False, allow_nan=False).encode("utf-8")
    except (TypeError, ValueError) as error:
        _fail("E_JSON", f"cannot encode canonical JSON: {error}")


def _load_canonical(path: Path) -> tuple[Any, bytes]:
    if path.is_symlink() or not path.is_file():
        _fail("E_PATH", f"not a regular file: {path}")
    try:
        raw = path.read_bytes()
        text = raw.decode("utf-8")
        value = json.loads(text, object_pairs_hook=_json_pairs, parse_constant=_nonfinite)
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        _fail("E_JSON", f"cannot load {path}: {error}")
    if not raw.endswith(b"\n") or raw.endswith(b"\n\n") or raw != _canonical(value) + b"\n":
        _fail("E_CANONICAL_JSON", f"{path} must be canonical JSON with one final LF")
    return value, raw


def _digest(raw: bytes) -> str:
    return hashlib.sha256(raw).hexdigest()


def _safe_relative(value: Any, expected: str, label: str) -> str:
    if type(value) is not str:
        _fail("E_PATH", f"{label} must be a relative POSIX path")
    p = PurePosixPath(value)
    if p.is_absolute() or ".." in p.parts or value != expected:
        _fail("E_PATH", f"{label} differs from expected path {expected!r}")
    return value


def _verify_ref(ref: Any, *, expected_path: str, raw: bytes, label: str) -> None:
    _exact(ref, REF_KEYS, label)
    _safe_relative(ref["path"], expected_path, label + ".path")
    if _natural(ref["bytes"], label + ".bytes") != len(raw):
        _fail("E_BYTES", f"{label} byte count differs")
    digest = ref["sha256"]
    if type(digest) is not str or not HEX64.fullmatch(digest) or digest != _digest(raw):
        _fail("E_HASH", f"{label} SHA-256 differs")


def _source_value(family: str, size: int) -> str:
    body = "Sort 0" if family == "pi" else f"x{size - 1:03d}"
    for i in range(size - 1, -1, -1):
        if family == "pi":
            body = f"(forall (x{i:03d} : Sort 0), {body})"
        else:
            rhs = "Sort 0" if i == 0 else f"x{i - 1:03d}"
            body = f"(let x{i:03d} : Sort 1 := {rhs}; {body})"
    return body


def render_source(family: str, size: int) -> bytes:
    """Render the protocol's exact one-definition source bytes."""
    if type(family) is not str or family not in {"pi", "let"} or type(size) is not int or size < 1:
        _fail("E_CASE", "source renderer requires family pi/let and positive integer size")
    ident = f"{family}{size:03d}"
    text = ("-- Generated by resource-envelope-pilot-1; exact scientific input.\n"
            "namespace ResourceEnvelopePilot1\n\n"
            f"def {ident} : Sort 1 := {_source_value(family, size)}\n\n"
            "end ResourceEnvelopePilot1\n")
    return text.encode("ascii")


def _expected_value(family: str, size: int) -> dict[str, Any]:
    if family == "pi":
        body: dict[str, Any] = {"tag": "sort", "level": 0}
        for i in range(size - 1, -1, -1):
            body = {"tag": "pi", "name": f"x{i:03d}",
                    "domain": {"tag": "sort", "level": 0}, "body": body}
        return body
    body = {"tag": "bvar", "index": 0}
    for i in range(size - 1, -1, -1):
        value: dict[str, Any] = ({"tag": "sort", "level": 0} if i == 0
                                 else {"tag": "bvar", "index": 0})
        body = {"tag": "let", "name": f"x{i:03d}",
                "type": {"tag": "sort", "level": 1}, "value": value, "body": body}
    return body


def _strict_lines(raw: bytes) -> list[dict[str, Any]]:
    if not raw.endswith(b"\n") or raw.endswith(b"\n\n") or b"\r" in raw:
        _fail("E_EXPORT_FORMAT", "export must end in exactly one LF and contain no CR")
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as error:
        _fail("E_EXPORT_FORMAT", f"export is not UTF-8: {error}")
    lines = text[:-1].split("\n")
    if any(not line for line in lines):
        _fail("E_EXPORT_FORMAT", "export contains an empty record line")
    rows: list[dict[str, Any]] = []
    for n, line in enumerate(lines):
        try:
            row = json.loads(line, object_pairs_hook=_json_pairs, parse_constant=_nonfinite)
        except (json.JSONDecodeError, AuditError) as error:
            _fail("E_EXPORT_FORMAT", f"invalid export record {n}: {error}")
        if type(row) is not dict:
            _fail("E_EXPORT_FORMAT", f"record {n} is not an object")
        rows.append(row)
    return rows


_EXPORT_META = {
    "meta": {
        "exporter": {"name": "lean4export", "version": "3.1.0"},
        "format": {"version": "3.1.0"},
        "lean": {"githash": "f72c35b3f637c8c6571d353742168ab66cc22c00",
                 "version": "4.29.1"},
    }
}
_EXPORT_META_LINE = (b'{"meta":{"exporter":{"name":"lean4export","version":"3.1.0"},'
                     b'"format":{"version":"3.1.0"},"lean":{"githash":'
                     b'"f72c35b3f637c8c6571d353742168ab66cc22c00","version":"4.29.1"}}}\n')


def _parse_export(raw: bytes, declaration: str) -> tuple[dict[int, dict[str, Any]], dict[int, str], dict[int, int], dict[str, Any]]:
    if not raw.startswith(_EXPORT_META_LINE):
        _fail("E_EXPORT_META_BYTES", "first metadata record must match the exact 173-byte line")
    rows = _strict_lines(raw)
    if len(rows) < 2 or rows[0] != _EXPORT_META or list(rows[0]) != ["meta"]:
        _fail("E_EXPORT_META", "first record is not the exact pinned producer/format metadata")
    if list(rows[-1]) != ["def"]:
        _fail("E_DECLARATIONS", "the only definition must be the final record")
    exprs: dict[int, dict[str, Any]] = {}
    names: dict[int, tuple[int, str]] = {}
    levels: dict[int, tuple[str, Any]] = {}
    name_structures: set[tuple[int, str]] = set()
    level_structures: set[tuple[str, int]] = set()
    expr_structures: set[bytes] = set()
    for pos, row in enumerate(rows[1:-1], 1):
        present = [tag for tag in ("in", "il", "ie") if tag in row]
        if len(present) != 1:
            _fail("E_EXPORT_RECORD", f"record {pos} must have exactly one permitted record tag")
        kind = present[0]
        if kind == "in":
            _exact(row, {"in", "str"}, f"record {pos}")
            ident = _natural(row["in"], "name ID")
            _exact(row["str"], {"pre", "str"}, "name node")
            pre = _natural(row["str"]["pre"], "name prefix ID")
            segment = row["str"]["str"]
            if ident != len(names) + 1:
                _fail("E_ID_SEQUENCE", "name IDs must be continuous from 1")
            if pre != 0 and pre not in names:
                _fail("E_FORWARD_REF", "name prefix must refer to an earlier name record")
            if type(segment) is not str or not segment:
                _fail("E_NAME", "invalid name segment")
            if (pre, segment) in name_structures:
                _fail("E_DUP_RECORD", "duplicate structural name node")
            name_structures.add((pre, segment))
            names[ident] = (pre, segment)
        elif kind == "il":
            _exact(row, {"il", "succ"}, f"record {pos}")
            ident = _natural(row["il"], "level ID")
            succ = _natural(row["succ"], "successor level")
            if ident != len(levels) + 1:
                _fail("E_ID_SEQUENCE", "level IDs must be continuous from 1")
            if succ != 0 and succ not in levels:
                _fail("E_FORWARD_REF", "level successor must refer to an earlier level record")
            if ("succ", succ) in level_structures:
                _fail("E_DUP_RECORD", "duplicate structural level node")
            level_structures.add(("succ", succ))
            levels[ident] = ("succ", succ)
        elif kind == "ie":
            ident = _natural(row["ie"], "expression ID")
            if ident != len(exprs):
                _fail("E_ID_SEQUENCE", "expression IDs must be continuous from 0")
            fields = set(row) - {"ie"}
            if len(fields) != 1:
                _fail("E_EXPR", "expression record must have exactly one expression tag")
            tag = next(iter(fields))
            payload = row[tag]
            if tag == "sort":
                if type(payload) is not int or payload < 0:
                    _fail("E_LEVEL", "sort level reference must be a natural integer")
                if payload != 0 and payload not in levels:
                    _fail("E_FORWARD_REF", "sort level must refer to an earlier level record")
            elif tag == "bvar":
                _natural(payload, "bound variable index")
            elif tag == "forallE":
                _exact(payload, {"binderInfo", "body", "name", "type"}, "forallE")
                if payload["binderInfo"] != "default":
                    _fail("E_BINDER_INFO", "Pi binder information is not default")
                for key in ("body", "name", "type"):
                    _natural(payload[key], "forallE." + key)
                if payload["name"] not in names:
                    _fail("E_FORWARD_REF", "Pi name must refer to an earlier name record")
                if payload["type"] not in exprs or payload["body"] not in exprs:
                    _fail("E_FORWARD_REF", "Pi children must refer to earlier expression records")
            elif tag == "letE":
                _exact(payload, {"body", "name", "nondep", "type", "value"}, "letE")
                if payload["nondep"] is not False:
                    _fail("E_LET_NONDEP", "let nondep must be exactly false")
                for key in ("body", "name", "type", "value"):
                    _natural(payload[key], "letE." + key)
                if payload["name"] not in names:
                    _fail("E_FORWARD_REF", "let name must refer to an earlier name record")
                if any(payload[key] not in exprs for key in ("type", "value", "body")):
                    _fail("E_FORWARD_REF", "let children must refer to earlier expression records")
            else:
                _fail("E_EXPR_TAG", f"expression tag {tag!r} is outside the frozen fragment")
            structure = _canonical({tag: payload})
            if structure in expr_structures:
                _fail("E_DUP_RECORD", "duplicate structural expression node")
            expr_structures.add(structure)
            exprs[ident] = {"tag": tag, "payload": payload}
        else:
            _fail("E_EXPORT_RECORD", f"record kind {kind!r} is not permitted")
    definition = rows[-1]["def"]
    _exact(definition, {"all", "hints", "levelParams", "name", "safety", "type", "value"}, "definition")
    if definition["safety"] != "safe":
        _fail("E_UNSAFE", "selected declaration is not marked safe")
    _exact(definition["hints"], {"regular"}, "definition hints")
    if _natural(definition["hints"]["regular"], "definition.hints.regular") != 1:
        _fail("E_DEF_HINTS", "definition reducibility hints differ from the exact source contract")
    if definition["levelParams"] != []:
        _fail("E_LEVEL_PARAMS", "definition has universe parameters")
    for key in ("name", "type", "value"):
        _natural(definition[key], "definition." + key)
    if definition["name"] not in names:
        _fail("E_FORWARD_REF", "definition name must refer to an earlier name record")
    if definition["type"] not in exprs or definition["value"] not in exprs:
        _fail("E_FORWARD_REF", "definition type/value must refer to earlier expression records")
    if (not isinstance(definition["all"], list) or len(definition["all"]) != 1
            or _natural(definition["all"][0], "definition.all[0]") != definition["name"]):
        _fail("E_DECLARATIONS", "definition all-list must contain only its own name")

    def resolve_name(ident: int, active: set[int] | None = None) -> tuple[str, ...]:
        if ident == 0:
            return ()
        parts: list[str] = []
        seen: set[int] = set()
        current = ident
        while current:
            if current not in names:
                _fail("E_NAME_REF", f"missing name ID {current}")
            if current in seen:
                _fail("E_CYCLE", "cyclic name prefix graph")
            seen.add(current)
            pre, part = names[current]
            parts.append(part)
            current = pre
            if len(parts) > 8:
                _fail("E_NAME", "name prefix depth exceeds the bounded source names")
        return tuple(reversed(parts))

    def resolve_level(ident: int, active: set[int] | None = None) -> int:
        value = 0
        seen: set[int] = set()
        current = ident
        while current:
            if current not in levels:
                _fail("E_LEVEL_REF", f"missing level ID {current}")
            if current in seen:
                _fail("E_CYCLE", "cyclic level successor graph")
            seen.add(current)
            kind, parent = levels[current]
            if kind != "succ":
                _fail("E_LEVEL", f"unsupported level constructor {kind}")
            current = parent
            value += 1
            if value > 1:
                _fail("E_LEVEL", "universe level exceeds the exact 0/1 fragment")
        return value

    if resolve_name(definition["name"]) != tuple(declaration.split(".")):
        _fail("E_DECL_NAME", "definition name differs from case declaration")
    # Validate all name/level nodes, including nodes that would otherwise be unused.
    resolved_names = {ident: resolve_name(ident) for ident in names}
    resolved_levels = {ident: resolve_level(ident) for ident in levels}
    if not exprs:
        _fail("E_EXPR", "export contains no expressions")

    def matches_formula(root: int, expected: dict[str, Any]) -> bool:
        pending = [(root, expected)]
        while pending:
            ident, want = pending.pop()
            if ident not in exprs:
                _fail("E_EXPR_REF", f"missing expression ID {ident}")
            actual = exprs[ident]
            tag, payload = actual["tag"], actual["payload"]
            wanted = want["tag"]
            if wanted == "sort":
                if tag != "sort" or resolve_level(payload) != want["level"]:
                    return False
            elif wanted == "bvar":
                if tag != "bvar" or payload != want["index"]:
                    return False
            elif wanted == "pi":
                if tag != "forallE" or resolved_names.get(payload["name"]) != (want["name"],):
                    return False
                pending.append((payload["type"], want["domain"]))
                pending.append((payload["body"], want["body"]))
            elif wanted == "let":
                if tag != "letE" or resolved_names.get(payload["name"]) != (want["name"],):
                    return False
                pending.append((payload["type"], want["type"]))
                pending.append((payload["value"], want["value"]))
                pending.append((payload["body"], want["body"]))
            else:
                _fail("E_EXPECTATION", f"unsupported expected constructor {wanted!r}")
        return True

    def check_scope(root: int) -> None:
        pending = [(root, 0)]
        seen: set[tuple[int, int]] = set()
        while pending:
            ident, depth = pending.pop()
            key = (ident, depth)
            if key in seen:
                continue
            seen.add(key)
            actual = exprs.get(ident)
            if actual is None:
                _fail("E_EXPR_REF", f"missing expression ID {ident}")
            tag, payload = actual["tag"], actual["payload"]
            if tag == "bvar":
                if payload >= depth:
                    _fail("E_SCOPE", f"bound variable {payload} is out of scope at depth {depth}")
            elif tag == "forallE":
                pending.extend(((payload["type"], depth), (payload["body"], depth + 1)))
            elif tag == "letE":
                pending.extend(((payload["type"], depth), (payload["value"], depth),
                                (payload["body"], depth + 1)))

    expected_type = {"tag": "sort", "level": 1}
    if not matches_formula(definition["type"], expected_type):
        _fail("E_EXPECTED_TYPE", "definition type is not exactly Sort 1")
    expected_value = _expected_value(_case_family_for_decl(declaration),
                                     _case_size_for_decl(declaration))
    check_scope(definition["value"])
    if not matches_formula(definition["value"], expected_value):
        _fail("E_EXPECTATION", "exported value differs from the independent family formula")

    # Reachability is checked separately for both declaration roots. This rejects
    # dead records that might otherwise conceal unrelated declarations or data.
    def visit_expr(root: int) -> set[int]:
        seen: set[int] = set()
        stack = [root]
        while stack:
            ident = stack.pop()
            if ident in seen:
                continue
            if ident not in exprs:
                _fail("E_EXPR_REF", f"missing expression ID {ident}")
            seen.add(ident)
            record = exprs[ident]
            tag, payload = record["tag"], record["payload"]
            if tag in {"forallE", "letE"}:
                for key in (("type", "body") if tag == "forallE" else ("type", "value", "body")):
                    stack.append(payload[key])
            elif tag == "sort" and payload != 0:
                resolve_level(payload)
        return seen

    value_ids = visit_expr(definition["value"])
    type_ids = visit_expr(definition["type"])
    used_name_ids = {definition["name"]}
    used_level_ids: set[int] = set()
    for ident in value_ids | type_ids:
        row = exprs[ident]
        if row["tag"] in {"forallE", "letE"}:
            payload = row["payload"]
            used_name_ids.add(payload["name"])
        elif row["tag"] == "sort" and row["payload"] != 0:
            used_level_ids.add(row["payload"])
    # Close transitive name prefixes and level successors.
    pending = list(used_name_ids)
    while pending:
        ident = pending.pop()
        if ident not in names:
            _fail("E_NAME_REF", f"missing name ID {ident}")
        pre, _ = names[ident]
        if pre and pre not in used_name_ids:
            used_name_ids.add(pre)
            pending.append(pre)
    pending_levels = list(used_level_ids)
    while pending_levels:
        ident = pending_levels.pop()
        if ident not in levels:
            _fail("E_LEVEL_REF", f"missing level ID {ident}")
        kind, value = levels[ident]
        if kind == "succ" and value and value not in used_level_ids:
            used_level_ids.add(value)
            pending_levels.append(value)
    if set(exprs) != value_ids | type_ids or set(names) != used_name_ids or set(levels) != used_level_ids:
        _fail("E_DEAD_RECORD", "export has dead or unreferenced expression/name/level records")
    if resolved_names[definition["name"]] != tuple(declaration.split(".")):
        _fail("E_DECL_NAME", "declaration name changed during name-graph validation")
    return exprs, resolved_names, resolved_levels, definition


def _case_family_for_decl(declaration: str) -> str:
    suffix = declaration.rsplit(".", 1)[-1]
    if suffix.startswith("pi"):
        return "pi"
    if suffix.startswith("let"):
        return "let"
    _fail("E_DECL_NAME", "declaration name has no recognized family")


def _case_size_for_decl(declaration: str) -> int:
    suffix = declaration.rsplit(".", 1)[-1]
    digits = suffix[2:] if suffix.startswith("pi") else suffix[3:] if suffix.startswith("let") else ""
    if len(digits) != 3 or not digits.isdigit():
        _fail("E_DECL_NAME", "declaration name has no three-digit size")
    return int(digits)


def _expanded_nodes(exprs: dict[int, dict[str, Any]], root: int) -> int:
    memo: dict[int, int] = {}
    state: dict[int, int] = {}
    stack: list[tuple[int, bool]] = [(root, False)]
    while stack:
        ident, finished = stack.pop()
        if ident not in exprs:
            _fail("E_EXPR_REF", f"missing expression ID {ident}")
        if finished:
            row = exprs[ident]
            tag, payload = row["tag"], row["payload"]
            children = (() if tag in {"sort", "bvar"} else
                        (payload["type"], payload["body"]) if tag == "forallE" else
                        (payload["type"], payload["value"], payload["body"]))
            total = 1 + sum(memo[child] for child in children)
            if total > 1_000_000:
                _fail("E_RESOURCE", "expanded value node count exceeds auditor safety bound")
            memo[ident] = total
            state[ident] = 2
            continue
        if state.get(ident) == 2:
            continue
        if state.get(ident) == 1:
            _fail("E_CYCLE", "cycle in expanded-size traversal")
        state[ident] = 1
        stack.append((ident, True))
        row = exprs[ident]
        tag, payload = row["tag"], row["payload"]
        children = (() if tag in {"sort", "bvar"} else
                    (payload["type"], payload["body"]) if tag == "forallE" else
                    (payload["type"], payload["value"], payload["body"]))
        for child in reversed(children):
            if state.get(child) == 1:
                _fail("E_CYCLE", "cycle in expanded-size traversal")
            if state.get(child) != 2:
                stack.append((child, False))
    return memo[root]


def _binder_depth(exprs: dict[int, dict[str, Any]], root: int) -> int:
    maximum = 0
    stack = [(root, 0)]
    while stack:
        ident, depth = stack.pop()
        row = exprs[ident]
        tag, payload = row["tag"], row["payload"]
        if tag in {"sort", "bvar"}:
            continue
        if tag == "forallE":
            stack.append((payload["type"], depth))
            stack.append((payload["body"], depth + 1))
            maximum = max(maximum, depth + 1)
        elif tag == "letE":
            stack.append((payload["type"], depth))
            stack.append((payload["value"], depth))
            stack.append((payload["body"], depth + 1))
            maximum = max(maximum, depth + 1)
    return maximum


def _expected_metrics(export_bytes: bytes, exprs: dict[int, dict[str, Any]], definition: dict[str, Any]) -> dict[str, int]:
    root = definition["value"]
    seen: set[int] = set()
    stack = [root]
    while stack:
        ident = stack.pop()
        if ident in seen:
            continue
        seen.add(ident)
        row = exprs[ident]
        tag, payload = row["tag"], row["payload"]
        if tag == "forallE":
            stack.extend((payload["type"], payload["body"]))
        elif tag == "letE":
            stack.extend((payload["type"], payload["value"], payload["body"]))
    return {"serialized_bytes": len(export_bytes), "reachable_dag_nodes": len(seen),
            "expanded_value_nodes": _expanded_nodes(exprs, root),
            "binder_depth": _binder_depth(exprs, root), "dependency_declarations": 0}


def audit_case(case_row: Any, export_bytes: bytes, source_bytes: bytes) -> dict[str, Any]:
    """Audit one case and exact raw bytes. Stable result contains no paths/times."""
    row = _exact(case_row, CASE_KEYS, "case row")
    if type(row["schema_version"]) is not int or row["schema_version"] != 1:
        _fail("E_SCHEMA", "case schema_version must be integer 1")
    ident = row["id"]
    if type(ident) is not str or not ident or "/" in ident or "\\" in ident:
        _fail("E_CASE", "case ID must be a single safe path component")
    ordinal = _natural(row["ordinal"], "ordinal")
    family, size = row["family"], _natural(row["size"], "size")
    if type(family) is not str or family not in {"pi", "let"} or size < 1:
        _fail("E_CASE", "family must be pi/let and size positive")
    suffix = f"{family}{size:03d}"
    declaration = f"ResourceEnvelopePilot1.{suffix}"
    if row["declaration"] != declaration or row["expected_type"] != "Sort 1":
        _fail("E_CASE", "declaration or expected type differs from frozen family rule")
    _natural(ordinal, "ordinal")
    _verify_ref(row["source"], expected_path=f"corpus/sources/{ident}.lean",
                raw=source_bytes, label="source")
    _verify_ref(row["export"], expected_path=f"corpus/exports/{ident}.ndjson",
                raw=export_bytes, label="export")
    expected_source = render_source(family, size)
    if source_bytes != expected_source:
        _fail("E_SOURCE", "source bytes differ from independently rendered exact template")
    exprs, _, _, definition = _parse_export(export_bytes, declaration)
    calculated = _expected_metrics(export_bytes, exprs, definition)
    metrics = _exact(row["metrics"], METRIC_KEYS, "metrics")
    for key, actual in calculated.items():
        if _natural(metrics[key], "metrics." + key) != actual:
            _fail("E_METRICS", f"metric {key} differs: expected {actual}")
    n = size
    expected_expanded = 2 * n + 1 if family == "pi" else 3 * n + 1
    if calculated["expanded_value_nodes"] != expected_expanded or calculated["binder_depth"] != n:
        _fail("E_METRICS", "formula-derived expanded size or binder depth differs")
    return {"status": "PASS", "id": ident, "family": family, "size": size,
            **calculated}


def _case_id(family: str, size: int) -> str:
    return f"rep1-{family}-{size:03d}"


def _expected_cases() -> list[dict[str, Any]]:
    cases = []
    ordinal = 0
    for family in ("pi", "let"):
        for size in (16, 32, 64, 128, 256, 512):
            cases.append({"id": _case_id(family, size), "ordinal": ordinal,
                          "family": family, "size": size})
            ordinal += 1
    return cases


def _load_exact_json(path: Path) -> tuple[Any, bytes]:
    return _load_canonical(path)


def _read_regular(path: Path) -> bytes:
    if path.is_symlink() or not path.is_file():
        _fail("E_PATH", f"not a regular file: {path}")
    try:
        return path.read_bytes()
    except OSError as error:
        _fail("E_PATH", f"cannot read {path}: {error}")


def _check_members(actual: set[str], expected: set[str], label: str) -> None:
    if actual != expected:
        _fail("E_CORPUS_MEMBERSHIP", f"{label} files differ from the fixed membership")


def _check_index_rows(rows: Any, expected: list[dict[str, Any]]) -> list[dict[str, Any]]:
    if type(rows) is not list or len(rows) != len(expected):
        _fail("E_INDEX", "index must contain exactly the expected number of cases")
    checked: list[dict[str, Any]] = []
    for want, got in zip(expected, rows, strict=True):
        _exact(got, INDEX_ROW_KEYS, "corpus index row")
        if (type(got["id"]) is not str or got["id"] != want["id"]
                or _natural(got["ordinal"], "index ordinal") != want["ordinal"]
                or type(got["family"]) is not str or got["family"] != want["family"]
                or _natural(got["size"], "index size") != want["size"]):
            _fail("E_INDEX_ORDER", "corpus index order/membership differs from fixed cohort")
        ref = _exact(got["case"], REF_KEYS, "index case ref")
        path = f"corpus/cases/{want['id']}.json"
        _safe_relative(ref["path"], path, "index case path")
        checked.append(got)
    return checked


def audit_corpus(corpus_dir: Path) -> dict[str, Any]:
    """Audit the fixed twelve exact source/export/case files and corpus index."""
    corpus_dir = Path(corpus_dir)
    if corpus_dir.is_symlink() or not corpus_dir.is_dir():
        _fail("E_CORPUS_PATH", "corpus root must be a regular directory")
    expected = _expected_cases()
    root_names = {p.name for p in corpus_dir.iterdir()}
    _check_members(root_names, {"index.json", "sources", "exports", "cases"}, "corpus root")
    expected_dirs = {"sources": {f"{x['id']}.lean" for x in expected},
                     "exports": {f"{x['id']}.ndjson" for x in expected},
                     "cases": {f"{x['id']}.json" for x in expected}}
    for dirname, names in expected_dirs.items():
        directory = corpus_dir / dirname
        if directory.is_symlink() or not directory.is_dir():
            _fail("E_CORPUS_PATH", f"missing regular {dirname} directory")
        actual = {p.name for p in directory.iterdir()}
        _check_members(actual, names, dirname)
    index_path = corpus_dir / "index.json"
    index, _ = _load_exact_json(index_path)
    _exact(index, INDEX_KEYS, "corpus index")
    if type(index["schema_version"]) is not int or index["schema_version"] != 1 or index["item_id"] != ITEM_ID:
        _fail("E_INDEX", "corpus index item/schema differs")
    checked_index_rows = _check_index_rows(index["cases"], expected)
    receipts: list[dict[str, Any]] = []
    for expect, index_row in zip(expected, checked_index_rows, strict=True):
        case_path = f"corpus/cases/{expect['id']}.json"
        case_file = corpus_dir / "cases" / f"{expect['id']}.json"
        row, row_bytes = _load_exact_json(case_file)
        _verify_ref(index_row["case"], expected_path=case_path, raw=row_bytes, label="index case")
        export_raw = _read_regular(corpus_dir / "exports" / f"{expect['id']}.ndjson")
        source_raw = _read_regular(corpus_dir / "sources" / f"{expect['id']}.lean")
        details = audit_case(row, export_raw, source_raw)
        if (type(row["id"]) is not str or row["id"] != expect["id"]
                or _natural(row["ordinal"], "case ordinal") != expect["ordinal"]
                or type(row["family"]) is not str or row["family"] != expect["family"]
                or _natural(row["size"], "case size") != expect["size"]):
            _fail("E_COHORT", "case identifiers/order differ from exact selected membership")
        receipts.append(details)
    family_counts = {family: sum(1 for row in receipts if row["family"] == family)
                     for family in ("pi", "let")}
    return {"status": "PASS", "item_id": ITEM_ID, "count": len(receipts),
            "case_order": [row["id"] for row in receipts],
            "families": family_counts}
