"""Pure construction and receipt helpers for RESOURCE-ENVELOPE-PILOT-1.

This module does not run Lean, export a declaration, or select a scientific case
when imported. The construction controller gates those operations separately.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any


FAMILIES = ("pi", "let")
SIZES = (16, 32, 64, 128, 256, 512)
MODULE = "ResourceEnvelopePilot1"
BASE = "corpus"  # Case/index bindings are relative to the item result directory.
HEADER = "-- Generated by resource-envelope-pilot-1; exact scientific input.\n"


class ProducerError(ValueError):
    pass


def _natural(value: object, field: str) -> int:
    if type(value) is not int or value < 0:
        raise ProducerError(f"{field} must be a nonnegative integer")
    return value


def _family(value: object) -> str:
    if value not in FAMILIES:
        raise ProducerError("unknown family")
    return str(value)


def case_id(family: str, size: int) -> str:
    _family(family)
    _natural(size, "size")
    if size < 1 or size > 999:
        raise ProducerError("size out of source-name range")
    return f"rep1-{family}-{size:03d}"


def declaration_name(family: str, size: int) -> str:
    _family(family)
    _natural(size, "size")
    if size < 1 or size > 999:
        raise ProducerError("size out of declaration-name range")
    return f"{MODULE}.{family}{size:03d}"


def selected_slots() -> tuple[tuple[int, str, int], ...]:
    """The fixed ordinals; calling this does not render any term."""
    return tuple((ordinal, family, size)
                 for ordinal, (family, size) in enumerate(
                     (family, size) for family in FAMILIES for size in SIZES))


def render_value(family: str, size: int) -> str:
    """Render one tower; prefreeze tests must use disjoint synthetic sizes."""
    _family(family)
    _natural(size, "size")
    if size < 1 or size > 999:
        raise ProducerError("size out of renderer range")
    if family == "pi":
        body = "Sort 0"
        for i in range(size - 1, -1, -1):
            body = f"(forall (x{i:03d} : Sort 0), {body})"
    else:
        body = f"x{size - 1:03d}"
        for i in range(size - 1, -1, -1):
            rhs = "Sort 0" if i == 0 else f"x{i - 1:03d}"
            body = f"(let x{i:03d} : Sort 1 := {rhs}; {body})"
    return body


def render_source(family: str, size: int) -> bytes:
    value = render_value(family, size)
    name = f"{family}{size:03d}"
    source = (HEADER + f"namespace {MODULE}\n\n"
              + f"def {name} : Sort 1 := {value}\n\n"
              + f"end {MODULE}\n")
    return source.encode("ascii")


def canonical_json(data: object) -> bytes:
    return (json.dumps(data, sort_keys=True, ensure_ascii=False,
                       allow_nan=False, separators=(",", ":")) + "\n").encode("utf-8")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _object_pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ProducerError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def _export_graph(export_bytes: bytes) -> tuple[dict[int, dict[str, Any]], int]:
    """Read enough of lean4export to count graph nodes, without type inference.

    The independent auditor, in another module, is the authority for semantic
    shape and graph validity. This function is deliberately only a producer
    metric calculator.
    """
    try:
        text = export_bytes.decode("utf-8")
        if not text.endswith("\n") or "\r" in text:
            raise ProducerError("export line encoding")
        records = [json.loads(line, object_pairs_hook=_object_pairs,
                              parse_constant=lambda x: (_ for _ in ()).throw(ProducerError(x)))
                   for line in text.splitlines()]
    except (UnicodeError, json.JSONDecodeError) as exc:
        raise ProducerError("malformed export JSON") from exc
    exprs: dict[int, dict[str, Any]] = {}
    defn: dict[str, Any] | None = None
    for rec in records:
        if not isinstance(rec, dict):
            raise ProducerError("export record is not an object")
        if "ie" in rec:
            idx = _natural(rec["ie"], "expression ID")
            if idx in exprs:
                raise ProducerError("duplicate expression ID")
            exprs[idx] = rec
        if "def" in rec:
            if defn is not None or not isinstance(rec["def"], dict):
                raise ProducerError("duplicate or malformed definition")
            defn = rec["def"]
    if defn is None:
        raise ProducerError("missing definition")
    value = _natural(defn.get("value"), "definition value")
    if value not in exprs:
        raise ProducerError("missing value expression")
    return exprs, value


def value_metrics(export_bytes: bytes) -> tuple[int, int]:
    """Return reachable unique Expr IDs and expanded value-tree occurrences."""
    exprs, root = _export_graph(export_bytes)
    expanded: dict[int, int] = {}
    visiting: set[int] = set()
    stack: list[tuple[int, bool]] = [(root, False)]
    while stack:
        idx, finish = stack.pop()
        if idx in expanded:
            continue
        if idx not in exprs:
            raise ProducerError("dangling expression reference")
        rec = exprs[idx]
        kinds = [k for k in ("sort", "bvar", "forallE", "letE") if k in rec]
        if len(kinds) != 1:
            raise ProducerError("unsupported expression record")
        kind = kinds[0]
        if kind in ("sort", "bvar"):
            children: list[int] = []
        elif kind == "forallE":
            node = rec[kind]
            if not isinstance(node, dict):
                raise ProducerError("malformed forallE")
            children = [_natural(node.get(k), k) for k in ("type", "body")]
        else:
            node = rec[kind]
            if not isinstance(node, dict):
                raise ProducerError("malformed letE")
            children = [_natural(node.get(k), k) for k in ("type", "value", "body")]
        if finish:
            expanded[idx] = 1 + sum(expanded[child] for child in children)
            visiting.remove(idx)
        else:
            if idx in visiting:
                raise ProducerError("cyclic expression graph")
            visiting.add(idx)
            stack.append((idx, True))
            for child in reversed(children):
                if child not in expanded:
                    stack.append((child, False))
    return len(expanded), expanded[root]


def make_case_row(ordinal: int, family: str, size: int,
                  source_bytes: bytes, export_bytes: bytes) -> dict[str, Any]:
    """Package already-produced bytes; controller must gate selected calls."""
    _natural(ordinal, "ordinal")
    identifier = case_id(family, size)
    if source_bytes != render_source(family, size):
        raise ProducerError("source differs from exact template")
    reachable, expanded = value_metrics(export_bytes)
    return {
        "schema_version": 1,
        "id": identifier,
        "ordinal": ordinal,
        "family": family,
        "size": size,
        "declaration": declaration_name(family, size),
        "expected_type": "Sort 1",
        "source": {"path": f"{BASE}/sources/{identifier}.lean",
                   "bytes": len(source_bytes), "sha256": sha256(source_bytes)},
        "export": {"path": f"{BASE}/exports/{identifier}.ndjson",
                   "bytes": len(export_bytes), "sha256": sha256(export_bytes)},
        "metrics": {"serialized_bytes": len(export_bytes),
                    "reachable_dag_nodes": reachable,
                    "expanded_value_nodes": expanded,
                    "binder_depth": size,
                    "dependency_declarations": 0},
    }
